blank_issues_enabled: true
contact_links:
  - name: Problem with the plugin or the website
    url: https://github.com/fxunleashed/fx-unleashed/issues/new/choose
    about: This repo is for dashes, screensavers and car light data only.
